---
#
#Installing Nginx
#
- name: Install nginx
  become: yes
  yum:
   name: nginx
   state: present
# Create conf directory
- name: Create nginx conf.d directory
  file: path=etc/nginx/conf.d/
   state=directory
   mode=0755
# Add kibana.conf to conf.d
- name: Configure nginx for Kibana
  become: yes
  template:
   src=kibana.conf.j2
   dest=/etc/nginx/conf.d/kibana.conf
  register: nginx_needs_restart
#Enable Nginx service
- name: Enabling Nginx service
  become: yes
  systemd:
   name: nginx
   enabled: yes
#Starting Nginx service
- name: Starting Nginx service
  become: yes
  systemd:
   name: nginx
   state: started
   daemon_reload: yes
# Installing expect to handle prompts
- name: Installing Expect
  become: yes
  yum:
   name: expect
   state: present
#using shell + expect to create a new user
- name: Creating a new nginx user to access Kibana
  become: yes
  shell: |
    set timeout 10 
    spawn htpasswd -c /etc/nginx/htpasswd.users {{kibana_user}}    
    expect "New password:"
    send -- "{{kibana_password}}\r"
    expect "Re-type new password:"
    send -- "{{kibana_password}}\r"
    expect "Adding password for user {{kibana_user}}"
    sleep 3
    exit 0 
  args:
    executable: /usr/bin/expect
# Restart Nginx service
- name: Restart Nginx service
  become: yes
  systemd:
   name: nginx
   state: restarted
   daemon_reload: yes
                                               
